
% Set the paths
baseDir = '/Volumes/Vision/MRI/Sample_dMRI/'; % Update with path to clinical data
subIDs = {'0201'}; % change the name of identification number of the subject


%% Rename diffusion images in the folder rawdata/

kk = 1; % number of the subject

% change the name of the nifti files created by dcm2bids
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-01_dwi.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.nkk.gz']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-01_dwi.bvec ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.bvec']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-01_dwi.bval ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.bval']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-01_dwi.json ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.json']);

system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-04_dwi.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.nkk.gz']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-04_dwi.bvec ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.bvec']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-04_dwi.bval ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.bval']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-04_dwi.json ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.json']);

system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-07_dwi.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.nkk.gz']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-07_dwi.bvec ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.bvec']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-07_dwi.bval ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.bval']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-07_dwi.json ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.json']);

system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-08_dwi.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.nkk.gz']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-08_dwi.bvec ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.bvec']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-08_dwi.bval ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.bval']);
system(['mv ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_run-08_dwi.json ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.json']);


%% Merge the 97 and 98 directions with the same phase encoding direction in one single diffusion image

system(['fslmerge -t ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_AP.nkk.gz '...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.nkk.gz ']);

system(['fslmerge -t ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_PA.nkk.gz '...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.nkk.gz ' ...
    baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.nkk.gz ']);

% AP
system(['paste ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.bvec ' ...
   baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.bvec ' ...
   ' >> ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_AP.bvec '])

system(['paste ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_AP.bval ' ...
   baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_AP.bval ' ...
   ' >> ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_AP.bval '])

% PA
system(['paste ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.bvec ' ...
   baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.bvec ' ...
   ' >> ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_PA.bvec '])

system(['paste ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti97_PA.bval ' ...
   baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti98_PA.bval ' ...
   ' >> ' baseDir '/rawdata/sub-' subIDs{kk} '/ses-' ses{kk} '/dwi/sub-' subIDs{kk} '_ses-' ses{kk} '_dti_PA.bval '])

